inputs:
  home_csv: "data/load/test-home-load.csv"
  substation_csv: "data/substations.csv"

logging:
  log_file: "logs/application_test.log"

intermediate:
  road_edges: "out/interim/test_road_edges.csv"
  road_nodes: "out/interim/test_road_nodes.csv"

mapping:
  padding: 0.001
  home_to_road: "out/mapping/test_map_h2r.txt"
  road_to_home: "out/mapping/test_map_r2h.txt"

secnet:
  out_dir: "out/secnet/"
  base_transformer_id: 51121000000000000
  out_prefix: "test"
  secnet_args:
    separation: 50.0
    penalty: 0.5
    max_rating: 25000
    max_hops: 10

partitioning:
  padding: 0.001
  assignment_json: "out/interim/test_transformer_assignment.json"

primnet:
  out_dir: "out/primnet/"
  primnet_args:
    voltage_max: 1.05
    voltage_min: 0.90
    maximum_voltage_drop: 0.15
    conductor_resistance_per_km: 0.8625
    base_impedance: 39690
    maximum_branch_flow: 400
    max_feeder_number: 10
    max_feeder_capacity: 400
    relative_gap: 0.05
    verbose: true
    warm_start: true
    threads: 0